# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ab-service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ab-service.proto',
  package='com.flipkarthealthplus.marketplace.abService',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x61\x62-service.proto\x12,com.flipkarthealthplus.marketplace.abService\":\n\x10\x41\x42ServiceRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x16\n\x0e\x65xperimentName\x18\x02 \x01(\t\"\'\n\x11\x41\x42ServiceResponse\x12\x12\n\nbucketName\x18\x01 \x01(\t2\x9c\x01\n\tABService\x12\x8e\x01\n\tIsEnabled\x12>.com.flipkarthealthplus.marketplace.abService.ABServiceRequest\x1a?.com.flipkarthealthplus.marketplace.abService.ABServiceResponse\"\x00\x42\x02P\x01\x62\x06proto3'
)




_ABSERVICEREQUEST = _descriptor.Descriptor(
  name='ABServiceRequest',
  full_name='com.flipkarthealthplus.marketplace.abService.ABServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='com.flipkarthealthplus.marketplace.abService.ABServiceRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='experimentName', full_name='com.flipkarthealthplus.marketplace.abService.ABServiceRequest.experimentName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=124,
)


_ABSERVICERESPONSE = _descriptor.Descriptor(
  name='ABServiceResponse',
  full_name='com.flipkarthealthplus.marketplace.abService.ABServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucketName', full_name='com.flipkarthealthplus.marketplace.abService.ABServiceResponse.bucketName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['ABServiceRequest'] = _ABSERVICEREQUEST
DESCRIPTOR.message_types_by_name['ABServiceResponse'] = _ABSERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ABServiceRequest = _reflection.GeneratedProtocolMessageType('ABServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _ABSERVICEREQUEST,
  '__module__' : 'ab_service_pb2'
  # @@protoc_insertion_point(class_scope:com.flipkarthealthplus.marketplace.abService.ABServiceRequest)
  })
_sym_db.RegisterMessage(ABServiceRequest)

ABServiceResponse = _reflection.GeneratedProtocolMessageType('ABServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _ABSERVICERESPONSE,
  '__module__' : 'ab_service_pb2'
  # @@protoc_insertion_point(class_scope:com.flipkarthealthplus.marketplace.abService.ABServiceResponse)
  })
_sym_db.RegisterMessage(ABServiceResponse)


DESCRIPTOR._options = None

_ABSERVICE = _descriptor.ServiceDescriptor(
  name='ABService',
  full_name='com.flipkarthealthplus.marketplace.abService.ABService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=168,
  serialized_end=324,
  methods=[
  _descriptor.MethodDescriptor(
    name='IsEnabled',
    full_name='com.flipkarthealthplus.marketplace.abService.ABService.IsEnabled',
    index=0,
    containing_service=None,
    input_type=_ABSERVICEREQUEST,
    output_type=_ABSERVICERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ABSERVICE)

DESCRIPTOR.services_by_name['ABService'] = _ABSERVICE

# @@protoc_insertion_point(module_scope)
